select * from customer
limit 10;

--Q1. What is the total revenue generated by male vs. female customers?
SELECT GENDER, SUM(PURCHASE_AMOUNT) FROM customer
GROUP BY GENDER


--Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount FROM customer
WHERE DISCOUNT_APPLIED = 'Yes' AND purchase_amount >= (SELECT AVG(PURCHASE_AMOUNT) FROM CUSTOMER)


--Q3. Which are the top 5 products with the highest average review rating?
SELECT ITEM_PURCHASED, ROUND(AVG(REVIEW_RATING::NUMERIC),2) AS AVERAGE_REVIEW FROM CUSTOMER
GROUP BY ITEM_PURCHASED
ORDER BY AVG(REVIEW_RATING) DESC LIMIT 5


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT SHIPPING_TYPE, ROUND(AVG(PURCHASE_AMOUNT),2) FROM CUSTOMER
WHERE SHIPPING_TYPE IN ('Standard','Express')
GROUP BY SHIPPING_TYPE


--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers 
--and non-subscribers.
SELECT SUBSCRIPTION_STATUS, COUNT(CUSTOMER_ID) AS TOTAL_CUSTOMER, 
ROUND(AVG(PURCHASE_AMOUNT),2) AS AVG_SPEND, SUM(PURCHASE_AMOUNT) AS REVENUE FROM CUSTOMER
GROUP BY SUBSCRIPTION_STATUS
ORDER BY REVENUE


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT ITEM_PURCHASED, 
ROUND( SUM(CASE WHEN DISCOUNT_APPLIED = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2)
AS PURCHASE 
FROM CUSTOMER
GROUP BY ITEM_PURCHASED
ORDER BY PURCHASE DESC
LIMIT 5


--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, 
-- and show the count of each segment.
SELECT SEGMENT, SUM(TOTAL) AS COUNT FROM 
( SELECT CASE WHEN PREVIOUS_PURCHASES = 1 THEN 'New'
	          WHEN PREVIOUS_PURCHASES BETWEEN 2 and	10 THEN 'Returning'
		      ELSE 'Loyal'
	  END AS SEGMENT,
	  COUNT(PREVIOUS_PURCHASES) AS TOTAL
  FROM CUSTOMER
  GROUP BY PREVIOUS_PURCHASES
  order by count(PREVIOUS_PURCHASES) DESC )
GROUP BY SEGMENT


--Q8. What are the top 3 most purchased products within each category?
WITH T AS ( SELECT CATEGORY, ITEM_PURCHASED, COUNT(ITEM_PURCHASED) AS COUNT,
            ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY CATEGORY,COUNT(ITEM_PURCHASED) DESC) AS RNK
            FROM CUSTOMER
            GROUP BY CATEGORY, ITEM_PURCHASED
            ORDER BY CATEGORY, COUNT DESC, ITEM_PURCHASED )
SELECT * FROM T
WHERE RNK<=3


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT SUBSCRIPTION_STATUS, COUNT(CUSTOMER_ID) FROM CUSTOMER
WHERE PREVIOUS_PURCHASES > 5
GROUP BY SUBSCRIPTION_STATUS


--Q10. What is the revenue contribution of each age group? 
SELECT AGE_GROUP, SUM(PURCHASE_AMOUNT) AS REVENUE FROM CUSTOMER
GROUP BY AGE_GROUP
ORDER BY REVENUE DESC





